# Generated by Django 4.2.7 on 2025-09-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="twitchsecretsapp",
            name="is_valid",
            field=models.BooleanField(default=False, verbose_name="Is valid?"),
        ),
    ]
