# Generated by Django 4.2.7 on 2025-09-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0002_twitchsecretsapp_is_valid"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwitchBaseReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward_id",
                    models.CharField(max_length=255, verbose_name="Reward ID"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("cost", models.CharField(max_length=255, verbose_name="Cost")),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="Is enabled"),
                ),
                (
                    "use_tts",
                    models.BooleanField(default=False, verbose_name="User TTS"),
                ),
            ],
        ),
    ]
