import os

TWITCH_CLIENT_ID = os.getenv("TWITCH_CLIENT_ID")
TWITCH_CLIENT_SECRET = os.getenv("TWITCH_CLIENT_SECRET")
TWITCH_REDIRECT_URI = os.getenv("TWITCH_REDIRECT_URI")
TWITCH_SCOPES = os.getenv("TWITCH_SCOPES")
if TWITCH_SCOPES:
    TWITCH_SCOPES = TWITCH_SCOPES.split(",")
else:
    TWITCH_SCOPES = None
